baseurl = "https://willhanley.net/"
languageCode = "en-us"
title = "Will Hanley | Historical International Legal Computational"
theme = "parsa"
summaryLength = "10"
paginate = 6

publishDir = "docs"

# output
[outputs]
home = ["HTML", "RSS", "JSON"]

# CSS Plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"
[[params.plugins.css]]
link = "plugins/academic-icons/css/academicons.css"

# JS Plugins
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/headroom/headroom.js"
[[params.plugins.js]]
link = "plugins/instafeed/instafeed.min.js"
[[params.plugins.js]]
link = "plugins/masonry/masonry.js"
[[params.plugins.js]]
link = "plugins/reading-time/readingTime.min.js"
[[params.plugins.js]]
link = "plugins/smooth-scroll/smooth-scroll.js"
[[params.plugins.js]]
link = "plugins/search/fuse.min.js"
[[params.plugins.js]]
link = "plugins/search/mark.js"
[[params.plugins.js]]
link = "plugins/search/search.js"

# navigation
[[menu.main]]
name = "Will Hanley | Historical International Legal Computational"
url = ""
weight = 1
hasChildren = false

[[menu.main]]
name = "About"
url = "about"
weight = 2

# deult parameter
[params]
logo = "images/logo.png"
home = "Home"
# theme layout ( two layout is available, "1" and "2" )
layout = "1"
# Meta data
description = "This is meta description"
# Preloader
preloader = true
# search
search = true
# about author
author = "Will Hanley"
author_image = "images/kurelek-man.jpeg"
bio = "I’m a historian of the Middle East at Florida State University."
# Contact info
mobile = "850 912 9143"
email = "whanley@pm.me"
address = "440 Bellamy, 113 Collegiate Loop Tallahassee FL 32306-2200"
# Contact Form Action
contact_form_action = "#"
# Google Analitycs
google_analitycs_id = "Your ID"
# copyright
copyright = "Copyright CC BY-NC-SA 4.0"

# Instagram feed
[params.instafeed]
enable = false
access_token = "#"

# cookies
[params.cookies]
enable = false
expire_days = 2

# social site
[[params.social]]
  icon = "ti-twitter-alt"
  link = "https://twitter.com/HanleyWill"

[[params.social]]
  icon = "ti-github"
  link = "https://github.com/whanley"

[[params.social]]
  icon = "ai ai-orcid"
  link = "https://orcid.org/0000-0002-1832-6805"

[[params.social]]
  icon = "ai ai-zenodo"
  link = "https://zenodo.org/search?page=1&size=20&q=owners:%2020288&sort=-publication_date"